### ISSUE TITLE
Investigating State Management approach

### ISSUE THREAD

**Issue by CodeGTDLearn** [PauloPortfolio/flutter-shoppingapp#2]
**State Management**
1. Check the documentation
2. Check the current version of the package
3. Check if the current version has a real easier implementation than the previous version
4. Compare Provider, Mobix and Bloc

**Comment by CodeGTDLearn** [comment]
The State Management will be used, will be MobX

**Comment by voby** [comment]
Just curious, why Mobx and not GetX?

**Comment by PauloPortfolio** [comment]
The MovX.was.changes for GetX

**Comment by CodeGTDLearn** [comment]
> Just curious, why Mobx and not GetX?

The MobX and Modular was totally removed from the project. GetX has been.used not only in state.management, but also in dependency management and route management. Sorry, the documentation was not updated,it is updated right now.
